apiVersion: v1 
kind: ConfigMap 
metadata:
  name: fitness-configmap 
  namespace: {{ .Values.namespace | default "fitness-ns" }}
data:
  PORT: {{ .Values.app.port | quote }}
  HOST: {{ .Values.app.host | quote }}
  NODE_ENV: {{ .Values.app.nodeEnv | quote }}



    
