{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fitness-tracker-runtime-secrets
  namespace: {{ .Values.namespace | default "fitness-ns" }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName | quote }}
    kind: SecretStore
  target:
    name: {{ .Values.externalSecrets.targetSecretName | quote }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.externalSecrets.keys.mongodbUri | quote }}
      remoteRef:
        key: {{ .Values.externalSecrets.remoteSecretName | quote }}
        property: MONGODB_URI
    - secretKey: {{ .Values.externalSecrets.keys.datadogApiKey | quote }}
      remoteRef:
        key: {{ .Values.externalSecrets.remoteSecretName | quote }}
        property: DD_API_KEY
{{- end }}
