{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.externalSecrets.secretStoreName | quote }}
  namespace: {{ .Values.namespace | default "fitness-ns" }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.aws.region | quote }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.aws.serviceAccountName | quote }}
{{- end }}
