{{- if .Values.externalSecrets.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.aws.serviceAccountName | quote }}
  namespace: {{ .Values.namespace | default "fitness-ns" }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.aws.roleArn | quote }}
{{- end }}
